name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Copy files to server
      run: |
        scp -r ./* user@your_server_ip:/path/to/deploy

    - name: Copy .env to server
      run: |
        scp .env user@your_server_ip:/path/to/deploy/.env

    - name: Execute deploy script
      run: |
        ssh user@your_server_ip 'bash -s' < ./deploy_script.sh
